core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
rebase.autosquash=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
credential.helper=manager
core.editor="C:\\Program Files\\JetBrains\\PhpStorm 2019.1.1\\bin\\phpstorm64.exe" 
winupdater.recentlyseenversion=2.22.0.windows.1
user.email=Ali.m2h1379@yahoo.com
credential.helper=cache --timeout 7200
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/mohammadsepahi/prozhe.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
credential.helper=store
